<a href="https://colab.research.google.com/github/abhishekshingadiya/ML-cabinet/blob/main/0_Sharping_numpy_pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
!python --version

Python 3.7.12


## NUMPY

In [77]:
import numpy as np

In [78]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [79]:
print(arr)

[1 2 3 4 5]


In [80]:
type(arr)

numpy.ndarray

In [81]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [82]:
arr.shape

(5,)

In [83]:
arr[3]

4

In [84]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [85]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [86]:
arr[3:]=100
arr

array([  1,   2,   3, 100, 100])

In [87]:

val=2

arr[arr<3]

array([1, 2])

In [88]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)

In [90]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [91]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [92]:
np.random.rand(3,3)

array([[0.99752364, 0.94162587, 0.81774368],
       [0.20977913, 0.18155166, 0.80563324],
       [0.46382898, 0.33771301, 0.47618925]])

In [93]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[ 0.54720659,  1.00296776,  0.41265147, -0.05815764],
       [ 1.43030335,  0.66052207, -0.27014792, -0.64063769],
       [-0.63901954, -1.11261318, -0.68043451, -1.19885081],
       [-0.18194616,  0.17565219, -0.88553724,  2.25625871]])

In [94]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [95]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.19521103 0.75682733]
 [0.40527723 0.85967549]]


In [96]:
#indexing
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [97]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [98]:

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6],[9,10]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
# a[row index,col index]
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]])) 

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [99]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])
print(b)
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [100]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [101]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


In [102]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [103]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [104]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [105]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [106]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [107]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# PANDAS

In [108]:
import pandas as pd

In [109]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=["Column1","Column2","Column3","Coumn4"])

In [110]:
df.head()

Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [111]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Coumn4     3
Name: Row1, dtype: int64

In [112]:
df.iloc[:,:]

Column1  Column2  Column3  Coumn4
Row1        0        1        2       3
Row2        4        5        6       7
Row3        8        9       10      11
Row4       12       13       14      15
Row5       16       17       18      19

In [113]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [114]:
df['Column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Column1, dtype: int64

In [115]:
df=pd.read_csv('penguins_lter.csv')
df.head()

studyName  Sample Number                              Species  Region  \
0   PAL0708              1  Adelie Penguin (Pygoscelis adeliae)  Anvers   
1   PAL0708              2  Adelie Penguin (Pygoscelis adeliae)  Anvers   
2   PAL0708              3  Adelie Penguin (Pygoscelis adeliae)  Anvers   
3   PAL0708              4  Adelie Penguin (Pygoscelis adeliae)  Anvers   
4   PAL0708              5  Adelie Penguin (Pygoscelis adeliae)  Anvers   

      Island               Stage Individual ID Clutch Completion  Date Egg  \
0  Torgersen  Adult, 1 Egg Stage          N1A1               Yes  11/11/07   
1  Torgersen  Adult, 1 Egg Stage          N1A2               Yes  11/11/07   
2  Torgersen  Adult, 1 Egg Stage          N2A1               Yes  11/16/07   
3  Torgersen  Adult, 1 Egg Stage          N2A2               Yes  11/16/07   
4  Torgersen  Adult, 1 Egg Stage          N3A1               Yes  11/16/07   

   Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  Body Mass (g)  \
0                39.1               18.7                181.0         3750.0   
1                39.5               17.4                186.0         3800.0   
2                40.3               18.0                195.0         3250.0   
3                 NaN                NaN                  NaN            NaN   
4                36.7               19.3                193.0         3450.0   

      Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
0    MALE                NaN                NaN   
1  FEMALE            8.94956          -24.69454   
2  FEMALE            8.36821          -25.33302   
3     NaN                NaN                NaN   
4  FEMALE            8.76651          -25.32426   

                         Comments  
0  Not enough blood for isotopes.  
1                             NaN  
2                             NaN  
3              Adult not sampled.  
4                             NaN

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   studyName            344 non-null    object 
 1   Sample Number        344 non-null    int64  
 2   Species              344 non-null    object 
 3   Region               344 non-null    object 
 4   Island               344 non-null    object 
 5   Stage                344 non-null    object 
 6   Individual ID        344 non-null    object 
 7   Clutch Completion    344 non-null    object 
 8   Date Egg             344 non-null    object 
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  334 non-null    object 
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    flo

In [117]:
df.describe()

Sample Number  Culmen Length (mm)  Culmen Depth (mm)  \
count     344.000000          342.000000         342.000000   
mean       63.151163           43.921930          17.151170   
std        40.430199            5.459584           1.974793   
min         1.000000           32.100000          13.100000   
25%        29.000000           39.225000          15.600000   
50%        58.000000           44.450000          17.300000   
75%        95.250000           48.500000          18.700000   
max       152.000000           59.600000          21.500000   

       Flipper Length (mm)  Body Mass (g)  Delta 15 N (o/oo)  \
count           342.000000     342.000000         330.000000   
mean            200.915205    4201.754386           8.733382   
std              14.061714     801.954536           0.551770   
min             172.000000    2700.000000           7.632200   
25%             190.000000    3550.000000           8.299890   
50%             197.000000    4050.000000           8.652405   
75%             213.000000    4750.000000           9.172123   
max             231.000000    6300.000000          10.025440   

       Delta 13 C (o/oo)  
count         331.000000  
mean          -25.686292  
std             0.793961  
min           -27.018540  
25%           -26.320305  
50%           -25.833520  
75%           -25.062050  
max           -23.787670

In [118]:
df['Species'].value_counts()

Adelie Penguin (Pygoscelis adeliae)          152
Gentoo penguin (Pygoscelis papua)            124
Chinstrap penguin (Pygoscelis antarctica)     68
Name: Species, dtype: int64

In [119]:
df.columns

Index(['studyName', 'Sample Number', 'Species', 'Region', 'Island', 'Stage',
       'Individual ID', 'Clutch Completion', 'Date Egg', 'Culmen Length (mm)',
       'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Sex',
       'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)', 'Comments'],
      dtype='object')

In [120]:
df[df['Flipper Length (mm)']>197.00]

studyName  Sample Number                              Species  Region  \
14    PAL0708             15  Adelie Penguin (Pygoscelis adeliae)  Anvers   
53    PAL0809             54  Adelie Penguin (Pygoscelis adeliae)  Anvers   
69    PAL0809             70  Adelie Penguin (Pygoscelis adeliae)  Anvers   
90    PAL0809             91  Adelie Penguin (Pygoscelis adeliae)  Anvers   
91    PAL0809             92  Adelie Penguin (Pygoscelis adeliae)  Anvers   
..        ...            ...                                  ...     ...   
338   PAL0910            119    Gentoo penguin (Pygoscelis papua)  Anvers   
340   PAL0910            121    Gentoo penguin (Pygoscelis papua)  Anvers   
341   PAL0910            122    Gentoo penguin (Pygoscelis papua)  Anvers   
342   PAL0910            123    Gentoo penguin (Pygoscelis papua)  Anvers   
343   PAL0910            124    Gentoo penguin (Pygoscelis papua)  Anvers   

        Island               Stage Individual ID Clutch Completion  Date Egg  \
14   Torgersen  Adult, 1 Egg Stage          N8A1               Yes  11/16/07   
53      Biscoe  Adult, 1 Egg Stage         N22A2               Yes   11/9/08   
69   Torgersen  Adult, 1 Egg Stage         N32A2                No  11/11/08   
90       Dream  Adult, 1 Egg Stage         N45A1               Yes  11/14/08   
91       Dream  Adult, 1 Egg Stage         N45A2               Yes  11/14/08   
..         ...                 ...           ...               ...       ...   
338     Biscoe  Adult, 1 Egg Stage         N38A1                No   12/1/09   
340     Biscoe  Adult, 1 Egg Stage         N39A1               Yes  11/22/09   
341     Biscoe  Adult, 1 Egg Stage         N39A2               Yes  11/22/09   
342     Biscoe  Adult, 1 Egg Stage         N43A1               Yes  11/22/09   
343     Biscoe  Adult, 1 Egg Stage         N43A2               Yes  11/22/09   

     Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  \
14                 34.6               21.1                198.0   
53                 42.0               19.5                200.0   
69                 41.8               19.4                198.0   
90                 35.7               18.0                202.0   
91                 41.1               18.1                205.0   
..                  ...                ...                  ...   
338                47.2               13.7                214.0   
340                46.8               14.3                215.0   
341                50.4               15.7                222.0   
342                45.2               14.8                212.0   
343                49.9               16.1                213.0   

     Body Mass (g)     Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
14          4400.0    MALE            8.55583          -25.22588   
53          4050.0    MALE            8.48095          -26.31460   
69          4450.0    MALE            8.86853          -26.06209   
90          3550.0  FEMALE            8.46531          -26.05621   
91          4300.0    MALE            8.77018          -25.83352   
..             ...     ...                ...                ...   
338         4925.0  FEMALE            7.99184          -26.20538   
340         4850.0  FEMALE            8.41151          -26.13832   
341         5750.0    MALE            8.30166          -26.04117   
342         5200.0  FEMALE            8.24246          -26.11969   
343         5400.0    MALE            8.36390          -26.15531   

                                  Comments  
14                                     NaN  
53                                     NaN  
69   Nest never observed with full clutch.  
90                                     NaN  
91                                     NaN  
..                                     ...  
338                                    NaN  
340                                    NaN  
341                                    NaN  
342                                    NaN  
3

In [121]:
df.corr()

Sample Number  Culmen Length (mm)  Culmen Depth (mm)  \
Sample Number             1.000000           -0.236356          -0.022352   
Culmen Length (mm)       -0.236356            1.000000          -0.235053   
Culmen Depth (mm)        -0.022352           -0.235053           1.000000   
Flipper Length (mm)       0.040849            0.656181          -0.583851   
Body Mass (g)            -0.007042            0.595110          -0.471916   
Delta 15 N (o/oo)         0.006952           -0.059759           0.605874   
Delta 13 C (o/oo)        -0.488690            0.189025           0.429933   

                     Flipper Length (mm)  Body Mass (g)  Delta 15 N (o/oo)  \
Sample Number                   0.040849      -0.007042           0.006952   
Culmen Length (mm)              0.656181       0.595110          -0.059759   
Culmen Depth (mm)              -0.583851      -0.471916           0.605874   
Flipper Length (mm)             1.000000       0.871202          -0.507787   
Body Mass (g)                   0.871202       1.000000          -0.537888   
Delta 15 N (o/oo)              -0.507787      -0.537888           1.000000   
Delta 13 C (o/oo)              -0.376223      -0.374638           0.570615   

                     Delta 13 C (o/oo)  
Sample Number                -0.488690  
Culmen Length (mm)            0.189025  
Culmen Depth (mm)             0.429933  
Flipper Length (mm)          -0.376223  
Body Mass (g)                -0.374638  
Delta 15 N (o/oo)             0.570615  
Delta 13 C (o/oo)             1.000000

In [122]:
lst_data=[[1,2,3],[3,4,np.nan],[5,6,np.nan],[6,np.nan,np.nan]]
df=pd.DataFrame(lst_data)
df.head()


0    1    2
0  1  2.0  3.0
1  3  4.0  NaN
2  5  6.0  NaN
3  6  NaN  NaN

In [123]:
df.dropna(axis=0)

0    1    2
0  1  2.0  3.0

In [124]:
lst_data=[[1,2,3],[3,4,np.nan],[5,6,np.nan],[6,np.nan,np.nan]]
df=pd.DataFrame(lst_data)
df.head()


0    1    2
0  1  2.0  3.0
1  3  4.0  NaN
2  5  6.0  NaN
3  6  NaN  NaN

In [125]:
df.dropna(axis=1)

0
0  1
1  3
2  5
3  6

In [126]:
df=pd.read_csv('penguins_lter.csv')
df.head()

studyName  Sample Number                              Species  Region  \
0   PAL0708              1  Adelie Penguin (Pygoscelis adeliae)  Anvers   
1   PAL0708              2  Adelie Penguin (Pygoscelis adeliae)  Anvers   
2   PAL0708              3  Adelie Penguin (Pygoscelis adeliae)  Anvers   
3   PAL0708              4  Adelie Penguin (Pygoscelis adeliae)  Anvers   
4   PAL0708              5  Adelie Penguin (Pygoscelis adeliae)  Anvers   

      Island               Stage Individual ID Clutch Completion  Date Egg  \
0  Torgersen  Adult, 1 Egg Stage          N1A1               Yes  11/11/07   
1  Torgersen  Adult, 1 Egg Stage          N1A2               Yes  11/11/07   
2  Torgersen  Adult, 1 Egg Stage          N2A1               Yes  11/16/07   
3  Torgersen  Adult, 1 Egg Stage          N2A2               Yes  11/16/07   
4  Torgersen  Adult, 1 Egg Stage          N3A1               Yes  11/16/07   

   Culmen Length (mm)  Culmen Depth (mm)  Flipper Length (mm)  Body Mass (g)  \
0                39.1               18.7                181.0         3750.0   
1                39.5               17.4                186.0         3800.0   
2                40.3               18.0                195.0         3250.0   
3                 NaN                NaN                  NaN            NaN   
4                36.7               19.3                193.0         3450.0   

      Sex  Delta 15 N (o/oo)  Delta 13 C (o/oo)  \
0    MALE                NaN                NaN   
1  FEMALE            8.94956          -24.69454   
2  FEMALE            8.36821          -25.33302   
3     NaN                NaN                NaN   
4  FEMALE            8.76651          -25.32426   

                         Comments  
0  Not enough blood for isotopes.  
1                             NaN  
2                             NaN  
3              Adult not sampled.  
4                             NaN

In [127]:
df2=df.reindex(df['Sample Number'])
df2.head()

studyName  Sample Number                              Species  \
Sample Number                                                                 
1               PAL0708              2  Adelie Penguin (Pygoscelis adeliae)   
2               PAL0708              3  Adelie Penguin (Pygoscelis adeliae)   
3               PAL0708              4  Adelie Penguin (Pygoscelis adeliae)   
4               PAL0708              5  Adelie Penguin (Pygoscelis adeliae)   
5               PAL0708              6  Adelie Penguin (Pygoscelis adeliae)   

               Region     Island               Stage Individual ID  \
Sample Number                                                        
1              Anvers  Torgersen  Adult, 1 Egg Stage          N1A2   
2              Anvers  Torgersen  Adult, 1 Egg Stage          N2A1   
3              Anvers  Torgersen  Adult, 1 Egg Stage          N2A2   
4              Anvers  Torgersen  Adult, 1 Egg Stage          N3A1   
5              Anvers  Torgersen  Adult, 1 Egg Stage          N3A2   

              Clutch Completion  Date Egg  Culmen Length (mm)  \
Sample Number                                                   
1                           Yes  11/11/07                39.5   
2                           Yes  11/16/07                40.3   
3                           Yes  11/16/07                 NaN   
4                           Yes  11/16/07                36.7   
5                           Yes  11/16/07                39.3   

               Culmen Depth (mm)  Flipper Length (mm)  Body Mass (g)     Sex  \
Sample Number                                                                  
1                           17.4                186.0         3800.0  FEMALE   
2                           18.0                195.0         3250.0  FEMALE   
3                            NaN                  NaN            NaN     NaN   
4                           19.3                193.0         3450.0  FEMALE   
5                           20.6                190.0         3650.0    MALE   

               Delta 15 N (o/oo)  Delta 13 C (o/oo)            Comments  
Sample Number                                                            
1                        8.94956          -24.69454                 NaN  
2                        8.36821          -25.33302                 NaN  
3                            NaN                NaN  Adult not sampled.  
4                        8.76651          -25.32426                 NaN  
5                        8.66496          -25.29805                 NaN

In [128]:
df2.fillna('Missing')

studyName  Sample Number                              Species  \
Sample Number                                                                 
1               PAL0708              2  Adelie Penguin (Pygoscelis adeliae)   
2               PAL0708              3  Adelie Penguin (Pygoscelis adeliae)   
3               PAL0708              4  Adelie Penguin (Pygoscelis adeliae)   
4               PAL0708              5  Adelie Penguin (Pygoscelis adeliae)   
5               PAL0708              6  Adelie Penguin (Pygoscelis adeliae)   
...                 ...            ...                                  ...   
120             PAL0910            121  Adelie Penguin (Pygoscelis adeliae)   
121             PAL0910            122  Adelie Penguin (Pygoscelis adeliae)   
122             PAL0910            123  Adelie Penguin (Pygoscelis adeliae)   
123             PAL0910            124  Adelie Penguin (Pygoscelis adeliae)   
124             PAL0910            125  Adelie Penguin (Pygoscelis adeliae)   

               Region     Island               Stage Individual ID  \
Sample Number                                                        
1              Anvers  Torgersen  Adult, 1 Egg Stage          N1A2   
2              Anvers  Torgersen  Adult, 1 Egg Stage          N2A1   
3              Anvers  Torgersen  Adult, 1 Egg Stage          N2A2   
4              Anvers  Torgersen  Adult, 1 Egg Stage          N3A1   
5              Anvers  Torgersen  Adult, 1 Egg Stage          N3A2   
...               ...        ...                 ...           ...   
120            Anvers  Torgersen  Adult, 1 Egg Stage         N66A1   
121            Anvers  Torgersen  Adult, 1 Egg Stage         N66A2   
122            Anvers  Torgersen  Adult, 1 Egg Stage         N67A1   
123            Anvers  Torgersen  Adult, 1 Egg Stage         N67A2   
124            Anvers  Torgersen  Adult, 1 Egg Stage         N69A1   

              Clutch Completion  Date Egg Culmen Length (mm)  \
Sample Number                                                  
1                           Yes  11/11/07               39.5   
2                           Yes  11/16/07               40.3   
3                           Yes  11/16/07            Missing   
4                           Yes  11/16/07               36.7   
5                           Yes  11/16/07               39.3   
...                         ...       ...                ...   
120                          No  11/17/09               36.2   
121                          No  11/17/09               37.7   
122                         Yes  11/16/09               40.2   
123                         Yes  11/16/09               41.4   
124                         Yes  11/18/09               35.2   

              Culmen Depth (mm) Flipper Length (mm) Body Mass (g)      Sex  \
Sample Number                                                                
1                          17.4               186.0        3800.0   FEMALE   
2                          18.0               195.0        3250.0   FEMALE   
3                       Missing             Missing       Missing  Missing   
4                          19.3               193.0        3450.0   FEMALE   
5                          20.6               190.0        3650.0     MALE   
...                         ...                 ...           ...      ...   
120                        17.2               187.0        3150.0   FEMALE   
121                        19.8               198.0        3500.0     MALE   
122                        17.0               176.0        3450.0   FEMALE   
123                        18.5               202.0        3875.0     MALE   
124                        15.9               186.0        3050.0   FEMALE   

              Delta 15 N (o/oo) Delta 13 C (o/oo)  \
Sample Number                                       
1                       8.94956         -24.69454   
2                       8.36821         -25.33302   
3              